language: php
php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4snapshot

env:
  - CODE_CHECKER_VERSION=^3.1

matrix:
  fast_finish: true

  allow_failures:
    - php: 7.4snapshot

  include:
    - php: 5.6
      env: COMPOSER_FLAG=--prefer-lowest CODE_CHECKER_VERSION=^2.13
    - php: 5.6
      env: COMPOSER_FLAG=--prefer-stable CODE_CHECKER_VERSION=^2.13
    - php: 7.0
      env: COMPOSER_FLAG=--prefer-lowest CODE_CHECKER_VERSION=^2.13
    - php: 7.0
      env: COMPOSER_FLAG=--prefer-stable CODE_CHECKER_VERSION=^2.13
    - php: 7.1
      env: COMPOSER_FLAG=--prefer-lowest
    - php: 7.1
      env: COMPOSER_FLAG=--prefer-stable
    - php: 7.2
      env: COMPOSER_FLAG=--prefer-lowest
    - php: 7.2
      env: COMPOSER_FLAG=--prefer-stable
    - php: 7.3
      env: COMPOSER_FLAG=--prefer-lowest
    - php: 7.3
      env: COMPOSER_FLAG=--prefer-stable

  exclude:
    - php: 5.6
      env: CODE_CHECKER_VERSION=^3.1
    - php: 7.0
      env: CODE_CHECKER_VERSION=^3.1

before_script:
  # Composer
  - travis_retry composer install --no-interaction
  # Coverage
  - if [[ "$TRAVIS_PHP_VERSION" == "7.0" && "$COMPOSER_FLAG" == "" ]]; then COVERAGE=1; fi

script:
  # Quality Assurance
  - composer run-script qa-linter
  - composer run-script qa-codesniffer

  # CodeChecker
  - composer create-project nette/code-checker temp/code-checker $CODE_CHECKER_VERSION --no-interaction
  - php temp/code-checker/src/code-checker.php --short-arrays

  # Nette\Tester
  - composer run-script qa-tester-info
  - composer run-script qa-tester

  # Nette\Tester + CodeCoverage
  - if [ "$COVERAGE" != "" ]; then composer run-script qa-tester-coverage-info; fi
  - if [ "$COVERAGE" != "" ]; then composer run-script qa-tester-coverage; fi

after_script:
  # Coverage (Coveralls)
  - if [ "$COVERAGE" != "" ]; then wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar; fi
  - if [ "$COVERAGE" != "" ]; then php coveralls.phar --verbose --config tests/.coveralls.yml; fi

after_failure:
  # Print *.actual content
  - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
